# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: qd_sdk.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='qd_sdk.proto',
  package='',
  syntax='proto3',
  serialized_options=_b('\312\002\027modules\\qd\\parse_log\\pb\342\002\034modules\\qd\\parse_log\\pb_meta'),
  serialized_pb=_b('\n\x0cqd_sdk.proto\"\xc2\x01\n\x0eQDSDKLogCommon\x12\r\n\x05\x61ppid\x18\x01 \x01(\t\x12\x0b\n\x03uid\x18\x02 \x01(\t\x12\n\n\x02os\x18\x03 \x01(\x05\x12\x0b\n\x03\x64id\x18\x04 \x01(\t\x12\n\n\x02\x64n\x18\x05 \x01(\t\x12\x0b\n\x03osv\x18\x06 \x01(\t\x12\x0c\n\x04sdkv\x18\x07 \x01(\t\x12\n\n\x02gv\x18\x08 \x01(\t\x12\x0c\n\x04imei\x18\t \x01(\t\x12\x0c\n\x04\x61\x64id\x18\n \x01(\t\x12\r\n\x05\x61ndid\x18\x0b \x01(\t\x12\x0f\n\x07\x63hannel\x18\x0c \x01(\t\x12\x0c\n\x04oaid\x18\r \x01(\t\"\xf6\x01\n\nQDSDKLogAd\x12\x1f\n\x06\x63ommon\x18\x01 \x01(\x0b\x32\x0f.QDSDKLogCommon\x12\x0c\n\x04type\x18\x02 \x01(\x05\x12\n\n\x02\x61\x64\x18\x03 \x01(\x05\x12\x0f\n\x07\x61\x64union\x18\x04 \x01(\x05\x12\x11\n\tadunionad\x18\x05 \x01(\t\x12\r\n\x05\x65vent\x18\x06 \x01(\t\x12%\n\x05\x65xtra\x18\x07 \x03(\x0b\x32\x16.QDSDKLogAd.ExtraEntry\x12\x10\n\x08req_time\x18\x08 \x01(\x03\x12\x13\n\x0breport_time\x18\t \x01(\x03\x1a,\n\nExtraEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x95\x01\n\x0cQDSDKLogPush\x12\x1f\n\x06\x63ommon\x18\x01 \x01(\x0b\x32\x0f.QDSDKLogCommon\x12\r\n\x05\x65vent\x18\x02 \x01(\t\x12\'\n\x05\x65xtra\x18\x03 \x03(\x0b\x32\x18.QDSDKLogPush.ExtraEntry\x1a,\n\nExtraEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\xba\x01\n\x0cQDSDKLogGame\x12\x1f\n\x06\x63ommon\x18\x01 \x01(\x0b\x32\x0f.QDSDKLogCommon\x12\x0b\n\x03rid\x18\x02 \x01(\t\x12\n\n\x02rn\x18\x03 \x01(\t\x12\n\n\x02rl\x18\x04 \x01(\x05\x12\r\n\x05\x65vent\x18\x05 \x01(\t\x12\'\n\x05\x65xtra\x18\x06 \x03(\x0b\x32\x18.QDSDKLogGame.ExtraEntry\x1a,\n\nExtraEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x42\x39\xca\x02\x17modules\\qd\\parse_log\\pb\xe2\x02\x1cmodules\\qd\\parse_log\\pb_metab\x06proto3')
)




_QDSDKLOGCOMMON = _descriptor.Descriptor(
  name='QDSDKLogCommon',
  full_name='QDSDKLogCommon',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='appid', full_name='QDSDKLogCommon.appid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='uid', full_name='QDSDKLogCommon.uid', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='os', full_name='QDSDKLogCommon.os', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='did', full_name='QDSDKLogCommon.did', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dn', full_name='QDSDKLogCommon.dn', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='osv', full_name='QDSDKLogCommon.osv', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sdkv', full_name='QDSDKLogCommon.sdkv', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gv', full_name='QDSDKLogCommon.gv', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='imei', full_name='QDSDKLogCommon.imei', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='adid', full_name='QDSDKLogCommon.adid', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='andid', full_name='QDSDKLogCommon.andid', index=10,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='channel', full_name='QDSDKLogCommon.channel', index=11,
      number=12, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='oaid', full_name='QDSDKLogCommon.oaid', index=12,
      number=13, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=211,
)


_QDSDKLOGAD_EXTRAENTRY = _descriptor.Descriptor(
  name='ExtraEntry',
  full_name='QDSDKLogAd.ExtraEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='QDSDKLogAd.ExtraEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='QDSDKLogAd.ExtraEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=416,
  serialized_end=460,
)

_QDSDKLOGAD = _descriptor.Descriptor(
  name='QDSDKLogAd',
  full_name='QDSDKLogAd',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='common', full_name='QDSDKLogAd.common', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='QDSDKLogAd.type', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ad', full_name='QDSDKLogAd.ad', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='adunion', full_name='QDSDKLogAd.adunion', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='adunionad', full_name='QDSDKLogAd.adunionad', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='event', full_name='QDSDKLogAd.event', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='extra', full_name='QDSDKLogAd.extra', index=6,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='req_time', full_name='QDSDKLogAd.req_time', index=7,
      number=8, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='report_time', full_name='QDSDKLogAd.report_time', index=8,
      number=9, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_QDSDKLOGAD_EXTRAENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=214,
  serialized_end=460,
)


_QDSDKLOGPUSH_EXTRAENTRY = _descriptor.Descriptor(
  name='ExtraEntry',
  full_name='QDSDKLogPush.ExtraEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='QDSDKLogPush.ExtraEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='QDSDKLogPush.ExtraEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=416,
  serialized_end=460,
)

_QDSDKLOGPUSH = _descriptor.Descriptor(
  name='QDSDKLogPush',
  full_name='QDSDKLogPush',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='common', full_name='QDSDKLogPush.common', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='event', full_name='QDSDKLogPush.event', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='extra', full_name='QDSDKLogPush.extra', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_QDSDKLOGPUSH_EXTRAENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=463,
  serialized_end=612,
)


_QDSDKLOGGAME_EXTRAENTRY = _descriptor.Descriptor(
  name='ExtraEntry',
  full_name='QDSDKLogGame.ExtraEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='QDSDKLogGame.ExtraEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='QDSDKLogGame.ExtraEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=416,
  serialized_end=460,
)

_QDSDKLOGGAME = _descriptor.Descriptor(
  name='QDSDKLogGame',
  full_name='QDSDKLogGame',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='common', full_name='QDSDKLogGame.common', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rid', full_name='QDSDKLogGame.rid', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rn', full_name='QDSDKLogGame.rn', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rl', full_name='QDSDKLogGame.rl', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='event', full_name='QDSDKLogGame.event', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='extra', full_name='QDSDKLogGame.extra', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_QDSDKLOGGAME_EXTRAENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=615,
  serialized_end=801,
)

_QDSDKLOGAD_EXTRAENTRY.containing_type = _QDSDKLOGAD
_QDSDKLOGAD.fields_by_name['common'].message_type = _QDSDKLOGCOMMON
_QDSDKLOGAD.fields_by_name['extra'].message_type = _QDSDKLOGAD_EXTRAENTRY
_QDSDKLOGPUSH_EXTRAENTRY.containing_type = _QDSDKLOGPUSH
_QDSDKLOGPUSH.fields_by_name['common'].message_type = _QDSDKLOGCOMMON
_QDSDKLOGPUSH.fields_by_name['extra'].message_type = _QDSDKLOGPUSH_EXTRAENTRY
_QDSDKLOGGAME_EXTRAENTRY.containing_type = _QDSDKLOGGAME
_QDSDKLOGGAME.fields_by_name['common'].message_type = _QDSDKLOGCOMMON
_QDSDKLOGGAME.fields_by_name['extra'].message_type = _QDSDKLOGGAME_EXTRAENTRY
DESCRIPTOR.message_types_by_name['QDSDKLogCommon'] = _QDSDKLOGCOMMON
DESCRIPTOR.message_types_by_name['QDSDKLogAd'] = _QDSDKLOGAD
DESCRIPTOR.message_types_by_name['QDSDKLogPush'] = _QDSDKLOGPUSH
DESCRIPTOR.message_types_by_name['QDSDKLogGame'] = _QDSDKLOGGAME
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

QDSDKLogCommon = _reflection.GeneratedProtocolMessageType('QDSDKLogCommon', (_message.Message,), dict(
  DESCRIPTOR = _QDSDKLOGCOMMON,
  __module__ = 'qd_sdk_pb2'
  # @@protoc_insertion_point(class_scope:QDSDKLogCommon)
  ))
_sym_db.RegisterMessage(QDSDKLogCommon)

QDSDKLogAd = _reflection.GeneratedProtocolMessageType('QDSDKLogAd', (_message.Message,), dict(

  ExtraEntry = _reflection.GeneratedProtocolMessageType('ExtraEntry', (_message.Message,), dict(
    DESCRIPTOR = _QDSDKLOGAD_EXTRAENTRY,
    __module__ = 'qd_sdk_pb2'
    # @@protoc_insertion_point(class_scope:QDSDKLogAd.ExtraEntry)
    ))
  ,
  DESCRIPTOR = _QDSDKLOGAD,
  __module__ = 'qd_sdk_pb2'
  # @@protoc_insertion_point(class_scope:QDSDKLogAd)
  ))
_sym_db.RegisterMessage(QDSDKLogAd)
_sym_db.RegisterMessage(QDSDKLogAd.ExtraEntry)

QDSDKLogPush = _reflection.GeneratedProtocolMessageType('QDSDKLogPush', (_message.Message,), dict(

  ExtraEntry = _reflection.GeneratedProtocolMessageType('ExtraEntry', (_message.Message,), dict(
    DESCRIPTOR = _QDSDKLOGPUSH_EXTRAENTRY,
    __module__ = 'qd_sdk_pb2'
    # @@protoc_insertion_point(class_scope:QDSDKLogPush.ExtraEntry)
    ))
  ,
  DESCRIPTOR = _QDSDKLOGPUSH,
  __module__ = 'qd_sdk_pb2'
  # @@protoc_insertion_point(class_scope:QDSDKLogPush)
  ))
_sym_db.RegisterMessage(QDSDKLogPush)
_sym_db.RegisterMessage(QDSDKLogPush.ExtraEntry)

QDSDKLogGame = _reflection.GeneratedProtocolMessageType('QDSDKLogGame', (_message.Message,), dict(

  ExtraEntry = _reflection.GeneratedProtocolMessageType('ExtraEntry', (_message.Message,), dict(
    DESCRIPTOR = _QDSDKLOGGAME_EXTRAENTRY,
    __module__ = 'qd_sdk_pb2'
    # @@protoc_insertion_point(class_scope:QDSDKLogGame.ExtraEntry)
    ))
  ,
  DESCRIPTOR = _QDSDKLOGGAME,
  __module__ = 'qd_sdk_pb2'
  # @@protoc_insertion_point(class_scope:QDSDKLogGame)
  ))
_sym_db.RegisterMessage(QDSDKLogGame)
_sym_db.RegisterMessage(QDSDKLogGame.ExtraEntry)


DESCRIPTOR._options = None
_QDSDKLOGAD_EXTRAENTRY._options = None
_QDSDKLOGPUSH_EXTRAENTRY._options = None
_QDSDKLOGGAME_EXTRAENTRY._options = None
# @@protoc_insertion_point(module_scope)
